// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://34uopl3cnzfbvdjxxyi53wu63m.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "eu-west-1:479b2bcb-b066-4e1b-8b0b-d073e0149fa4",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_N8kFNPjZj",
    "aws_user_pools_web_client_id": "27hvhju9fk2lsfebpsqh2mon2n",
    "oauth": {
        "domain": "monproweb24c7ff83-24c7ff83-prod.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://monproweb.com/",
        "redirectSignOut": "http://localhost:3000/,https://monproweb.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "BenderTordeurRodriguez_prod",
            "alias": "$LATEST",
            "region": "eu-west-1"
        }
    ],
    "aws_mobile_analytics_app_id": "a7740b56a68c49cba4487b14d27716bd",
    "aws_mobile_analytics_app_region": "eu-west-1"
};


export default awsmobile;
